server:
  port: 1013
spring:
  application:
    name: best-team-email-service
  rabbitmq:
    host: 192.168.6.132
    port: 5672
    username: yzy
    password: 123456
    virtual-host: test
  redis:
    jedis:
      pool:
        max-active: 20
    host: 192.168.6.132
    password: 123456
    port: 6379
dubbo:
  application:
    name: best-team-email-web1
  registry:
    address: zookeeper://192.168.6.132:2181
  protocol:
    port: 20887