server:
  port: 1011
#dubbo:
#  application:
#    name: shop-sms-web
#  registry:
#    address: zookeeper://192.168.6.132:2181
spring:
  rabbitmq:
    host: 192.168.6.132
    port: 5672
    username: yzy
    password: 123456
    virtual-host: test

