server:
  port: 1016
spring:
  redis:
    jedis:
      pool:
        max-active: 20
    host: 192.168.6.132
    password: 123456
    port: 6379
dubbo:
  application:
    name: beat-team-cart-web
  registry:
    address: zookeeper://192.168.6.132:2181