server:
  port: 2026
dubbo:
  application:
    name: beat-team-cart-web
  protocol:
    port: 20889
  registry:
    address: zookeeper://192.168.6.132:2181
spring:
  redis:
    jedis:
      pool:
        max-active: 20
    host: 192.168.6.132
    password: 123456
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/myshop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
