server:
  port: 2025
dubbo:
  application:
    name: beat-team-user-service
  registry:
    address: zookeeper://192.168.6.132:2181
  protocol:
    port: 20888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myshop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    jedis:
      pool:
        max-active: 20
    host: 192.168.6.132
    password: 123456
    port: 6379