server:
  port: 2024
dubbo:
  application:
    name: best-team-regist-service
  registry:
    address: zookeeper://192.168.6.132:2181
  protocol:
    port: 20881
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myshop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root